name: Build and Run Tests
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/envelop_test'
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE envelop_test;' -uroot -proot
          mysql -uroot -proot envelop_test < src/helpers/schema.sql
          mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
          mysql -uroot -proot -e "FLUSH PRIVILEGES;"
      - run: yarn install
      - run: yarn build
      - run: yarn test:all
