name: Create a Sentry release

on:
  push:
    branches:
      - 'main'

jobs:
  create-sentry-release:
    strategy:
      matrix:
        target: ['18']
    uses: snapshot-labs/actions/.github/workflows/create-sentry-release.yml@main
    secrets: inherit
    with:
      project: envelop
      target: ${{ matrix.target }}
